Introduce 'udevrules' inspection
rpminspect/rpminspect pull request #1172
Opened 2023-05-15 07:33 UTC by ldv-alt

The udevrules inspection checks udev rules files syntax using "udevadm verify".  The latter is a new udevadm tool command introduced in systemd v254.

2023-05-15 13:49 UTC, dcantrell requested changes
Just a string cleanup.

2023-05-15 13:49 UTC, dcantrell commented on include/results.h
> +#define REMEDY_UDEVRULES _("Refer to the udev documentation at https://www.freedesktop.org/software/systemd/man/udev.html for help correcting the errors and warnings")
Need a period after warnings.

2023-05-15 13:51 UTC, dcantrell commented
This looks really nice, thanks for the PR!

It might not be possible, but is 'udevadm verify' available via a library at all or is just only available as the command?

Given the requirement of systemd v254, the spec file template needs to carry a Requires for that.  If the packaging varies across Fedora, CentOS Stream, and RHEL, it might be best to just put the Requires on the individual command at >= 254.

Thanks!

2023-05-15 18:20 UTC, ldv-alt commented
> It might not be possible, but is 'udevadm verify' available via a library at all or is just only available as the command?

Unfortunately, systemd doesn't provide a library for parsing udev rules files.

> Given the requirement of systemd v254, the spec file template needs to carry a Requires for that. If the packaging varies across Fedora, CentOS Stream, and RHEL, it might be best to just put the Requires on the individual command at >= 254.

Given that systemd 254 has not been released yet, would it be OK to specify a requirement to an unreleased version?
Something along these lines?
```
# The udevrules inspection requires an external executable (udevadm verify)
# provided by systemd-udev.  If the installed udevadm executable does not
# provide 'verify' command, you can disable the udevrules inspection.
%if 0%{?rhel} >= 8 || 0%{?epel} >= 8 || 0%{?fedora}
Recommends:     systemd-udev >= 254
%else
Requires:       systemd-udev >= 254
%endif
```

2023-05-16 19:23 UTC, ldv-alt commented
OK, I've added a runtime check.

2023-05-21 18:57 UTC, ldv-alt commented
In the latest edition I've introduced run_udevadm_verify() wrapper to simplify `udevadm verify` invocation.
Also, I added --no-summary option to `udevadm verify` to turn off the summary which just clutters the output.

2023-05-22 17:17 UTC, ldv-alt commented
@dcantrell, is anything else expected from me in this PR?

2023-05-29 09:46 UTC, ldv-alt commented
@dcantrell, please let me know if something has to be changed in this PR.

2023-05-31 17:52 UTC, dcantrell commented
Everything looks good at this point.  I just want to see the CI jobs pass before merging it.

2023-05-31 18:26 UTC, ldv-alt commented
> Everything looks good at this point. I just want to see the CI jobs pass before merging it.

Hmm, CI seems to be broken for unrelated reasons.

2023-06-01 17:07 UTC, dcantrell approved these changes

2023-06-01 17:08 UTC, dcantrell commented
It's the Fedora rawhide Docker image that I use in GHA.  It is missing dnf5 as well as /etc/dnf/dnf.conf for dnf 4.x.  I've fixed that in my CI job definition, but there's also a bug to fix the Docker images for rawhide.

2023-06-01 18:19 UTC, merged