[fix] Honor case-insensitive SPDX names
rpminspect/rpminspect pull request #1341
Opened 2024-02-27 20:49 UTC by dcantrell

SPDX license names can be case-insensitive, but the boolean terms must be uppercase (thanks, spec!).  Ensure the license inspection honors this.

Fixes: #1335

2024-02-27 21:06 UTC, evan-goode requested changes

2024-02-27 21:06 UTC, evan-goode commented on include/results.h
> +#define REMEDY_INVALID_BOOLEAN _("The License tag contains SPDX license identifiers.  When SPDX identifiers are used, the boolean joining terms must be written in all capitable letters per the spec.
Typo: `capitable`

2024-02-28 13:12 UTC, dcantrell commented on include/results.h
> +#define REMEDY_INVALID_BOOLEAN _("The License tag contains SPDX license identifiers.  When SPDX identifiers are used, the boolean joining terms must be written in all capitable letters per the spec.
Done.

2024-02-28 13:17 UTC, evan-goode approved these changes

2024-02-28 14:13 UTC, jimbair approved these changes

2024-02-28 14:39 UTC, merged