[bld] Build libtoml sources without -Werror
rpminspect/rpminspect pull request #1365
Opened 2024-04-10 14:22 UTC by msrb

COPR builds for EPEL fail because the sources are compiled with -Werror. The problem is that the bundled libtoml sources don't compile when warnings are treated as errors.

The right thing to do would be to work with the libtoml upstream to fix the problems and make sure that they use -Werror as well. But this can take some time to achieve.

In the meantime, we compile the libtoml sources without -Werror.

2024-04-10 14:55 UTC, dcantrell requested changes
Change the libtoml asprintf() usage to xasprintf() as provided in the rpminspect headers.  Keep -Werror in place.

2024-04-10 16:03 UTC, msrb commented
@dcantrell I was thinking about just patching the bundled code, but do you expect any upstream rebases there?

2024-04-11 08:24 UTC, msrb commented
The last upstream commit is from 8 years ago... so I guess there won't be any "rebase to the latest upstream release" commits here :)

In that case, patching the code here is indeed the best thing to do -- I am on it ;)

2024-04-11 08:24 UTC, closed without merging

2024-04-11 12:07 UTC, msrb commented
Superseded by https://github.com/rpminspect/rpminspect/pull/1366.